function out1 = dPHIds_lift(dx,dy,mu,alpha,in5)
%dPHIds_lift
%    OUT1 = dPHIds_lift(DX,DY,MU,ALPHA,IN5)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    29-Nov-2025 12:43:31

%Version: 0.9
t2 = (alpha.*dx.*dy)./4.0;
t3 = -t2;
z = zeros(1,length(t3));
out1 = [z;t3;z;t3;z;t3;z;t3];
end
