function dphidg = dPHIdg_lift(dx,dy,mu,alpha,dalpha,in6)
%dPHIdg_lift
%    DPHIDG = dPHIdg_lift(DX,DY,MU,ALPHA,DALPHA,IN6)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    29-Nov-2025 12:43:31

%Version: 0.9
u2 = in6(2,:);
u4 = in6(4,:);
u6 = in6(6,:);
u8 = in6(8,:);
dphidg = dalpha.*dx.*dy.*(u2+u4+u6+u8).*(-1.0./4.0);
end
