function phi = PHI_lift(dx,dy,mu,alpha,in5)
%PHI_lift
%    PHI = PHI_lift(DX,DY,MU,ALPHA,IN5)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    29-Nov-2025 12:43:31

%Version: 0.9
u2 = in5(2,:);
u4 = in5(4,:);
u6 = in5(6,:);
u8 = in5(8,:);
phi = alpha.*dx.*dy.*(u2+u4+u6+u8).*(-1.0./4.0);
end
