function dphidg = dPHIdg_drag(dx,dy,mu,alpha,dalpha,in6)
%dPHIdg_drag
%    DPHIDG = dPHIdg_drag(DX,DY,MU,ALPHA,DALPHA,IN6)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    29-Nov-2025 10:53:42

%Version: 0.9
u1 = in6(1,:);
u3 = in6(3,:);
u5 = in6(5,:);
u7 = in6(7,:);
dphidg = (dalpha.*dx.*dy.*(u1+u3+u5+u7))./4.0;
end
