function out1 = dPHIds_drag(dx,dy,mu,alpha,in5)
%dPHIds_drag
%    OUT1 = dPHIds_drag(DX,DY,MU,ALPHA,IN5)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    29-Nov-2025 10:53:42

%Version: 0.9
t2 = (alpha.*dx.*dy)./4.0;
z = zeros(1,length(t2));
out1 = [t2; z; t2; z; t2; z; t2; z];
end
