function phi = PHI_drag(dx,dy,mu,alpha,in5)
%PHI_drag
%    PHI = PHI_drag(DX,DY,MU,ALPHA,IN5)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    29-Nov-2025 10:53:42

%Version: 0.9
u1 = in5(1,:);
u3 = in5(3,:);
u5 = in5(5,:);
u7 = in5(7,:);
phi = (alpha.*dx.*dy.*(u1+u3+u5+u7))./4.0;
end
